source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
use_frameworks!

target 'Marvel-Hero-demo' do
    pod 'AlamofireImage', '~> 3.5'
end

  target 'Marvel-Hero-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Marvel-Hero-demoUITests' do
    # Pods for testing
  end

